WiP: Azure porting
moio/scalability-tests pull request #18
Opened 2023-11-20 18:23 UTC by fgiudici

Still WiP, not working and not ready for review.

2023-11-22 17:02 UTC, fgiudici commented on terraform/modules/k3s/install_k3s.sh
> +sudo -s <<SUDO
This file is the only shared part I'm touching with this PR (it is also in a separate commit).
I'm pretty confident it should be safe as long as the host has 'sudo' command.
I can go with something more fancy (i.e., checking the user and the 'sudo' binary, and prepend all the commands with "sudo" when required) but the script would be a bit more convoluted, so I have a preference for the current solution.

2023-11-23 09:24 UTC, moio requested changes
Overall a great start, thanks @fgiudici !

Most comments are cosmetic or notes for later. Happy to merge as soon as they are addressed.

2023-11-23 09:24 UTC, moio commented on terraform/main/azure/main.tf
> +   * We need to wait for the module.network to complete before moving on to workaround
I am totally fine with this "workaround", just please prefix this comment with `HACK:` - that is the conventional way to mark code to be fixed when some external condition happens (in this case, the attached issue is solved).

Comment added to the developer readme:
https://github.com/moio/scalability-tests/blob/master/DEVELOPING.md#hacks-and-workarounds

2023-11-23 09:24 UTC, moio commented on terraform/main/azure/main.tf
> +/*
Please stash this code, I prefer not to commit commented-out code (unless they are examples meant to be uncommented by users).

2023-11-23 09:24 UTC, moio commented on terraform/main/azure/outputs.tf
> +      private_name         = module.cluster[i].first_server_private_name
Note for a future PR: latest commits added an optional `public_name` key here:

https://github.com/moio/scalability-tests/blame/master/terraform/main/aws/outputs.tf#L7

This will be needed as soon as we want to expose Rancher to the Internet, which IIUC is a precondition for AzureAD or other authentication framework.

Nothing for this PR though.

2023-11-23 09:24 UTC, moio commented on terraform/modules/azure_host/input.tf
> +variable "admin_username" {
Is this the name used for SSH connections? If so, I suggest renaming this variable to `ssh_user` for consistency with the ssh backend which already supports it.

Long term, we will probably want a PR to uniform all backends in this respect.

2023-11-23 09:24 UTC, moio commented on terraform/modules/azure_host/input.tf
> +  default     = null
Please add a type definition

2023-11-23 09:24 UTC, moio commented on terraform/modules/azure_host/input.tf
> +# TODO: commands should be actually applied
It seems to me they are, is this TODO comment still valid?

2023-11-23 09:24 UTC, moio commented on terraform/modules/azure_host/main.tf
> +  eviction_policy = "Deallocate"
I suggest these variables are exposed as vars, so that they can be leveraged in future.

Spot instances look very attractive for at-scale tests.

2023-11-23 09:24 UTC, moio commented on terraform/modules/azure_host/main.tf
> +    storage_account_type = "Standard_LRS"
Note for later: we will most likely need the ability to specify a directly-attached SSD disk for etcd nodes at some point.

2023-11-23 09:24 UTC, moio commented on terraform/modules/k3s/install_k3s.sh
> +sudo -s <<SUDO
OK for now. I will later test again the AWS backend and propose some fix if it breaks for any unexpected reason.

2023-11-23 13:40 UTC, fgiudici commented on terraform/main/azure/main.tf
> +/*
Oh, right, it is a leftover...

2023-11-23 13:53 UTC, moio commented on terraform/main/azure/inputs.tf
> +    instance_type = "Standard_B2as_v2"
You might want to rename `instance_type` to `size` - IIUC they are the same concept but the former is AWS jargon, while the later is Azure's

2023-11-23 14:32 UTC, fgiudici commented on terraform/modules/azure_host/input.tf
> +variable "admin_username" {
that variable tracks the name of  the (only) user which is created inside the Azure VM  which will have passwordless sudo powers (no root user allowed).
Yes, that's the user for ssh access, renaming it all around.

2023-11-23 14:37 UTC, fgiudici commented on terraform/modules/azure_host/input.tf
> +# TODO: commands should be actually applied
good catch, it is a leftover!

2023-11-23 14:40 UTC, fgiudici commented on terraform/modules/azure_host/main.tf
> +  eviction_policy = "Deallocate"
That's a good plan indeed.
I experimented with them at the beginning but started getting errors stating something like the number of cores for "Spot" instances have been exceeded... seems capped to 3 cores for our access (?!?). But something I have in my queue to investigate (that's why I left them there).

2023-11-23 15:05 UTC, fgiudici commented on terraform/main/azure/inputs.tf
> +    instance_type = "Standard_B2as_v2"
you got it right

2023-11-23 17:09 UTC, fgiudici commented on terraform/main/azure/main.tf
> +  required_version = "1.6.3"
kept 1.5.6 in this PR

2023-11-23 17:14 UTC, fgiudici commented on terraform/main/azure/outputs.tf
> +      private_name         = module.cluster[i].first_server_private_name
tracked in https://github.com/moio/scalability-tests/issues/22

2023-11-23 17:37 UTC, fgiudici commented on terraform/modules/azure_host/main.tf
> +  eviction_policy = "Deallocate"
There is actually a "quota" for Spot VM cores: https://learn.microsoft.com/en-us/azure/quotas/spot-quota

2023-11-23 17:46 UTC, fgiudici commented on terraform/modules/azure_host/main.tf
> +    storage_account_type = "Standard_LRS"
tracked in #23

2023-11-23 17:48 UTC, fgiudici commented
Added fixes and rebased, thanks for the ssh key fix @moio  🙇🏼

2023-11-24 08:00 UTC, moio commented on terraform/main/azure/inputs.tf
> +    Owner = "fgiudici"
Leftover spotted, I am fixing this directly

2023-11-24 08:09 UTC, moio approved these changes
Good to go!

2023-11-24 08:09 UTC, merged