feat(provider): add openstack support
moio/scalability-tests pull request #8
Opened 2023-08-24 09:39 UTC by Lucasgranet

Hello!

I added Openstack support for running Scalability-test.
Tested against OVH's Openstack.

This implementation is mostly based on the AWS one.

Let me know if there are any questions.

Lucas,

2023-08-25 13:14 UTC, moio commented
Wow, thank you so very much!

I need a bit of time to take a thorough look - I plan to come back with feedback sometime next week.

Have a nice weekend!

2023-08-28 12:29 UTC, moio requested changes
Great job @Lucasgranet!

I do not have much to object. There are a few "editorial" changes I would do but they are pure aesthetics, so I will do them myself before merging.

I left a few comments only for you to take a look.

Thanks again!

2023-08-28 12:29 UTC, moio commented on terraform/main/openstack/inputs.tf
> +  project_name = "lgr"
```suggestion
  project_name = "st"
```

Rationale: we standardized to "st" for all prefixes by default. You can make it an overridable variable if that helps.

2023-08-28 12:29 UTC, moio commented on terraform/main/openstack/inputs.tf
> +    flavor_name    = "b2-7" // 2vCPU/7Go
What is the difference with the `b2-7` instance above used for downstream clusters?

2023-08-28 12:29 UTC, moio commented on terraform/main/openstack/inputs.tf
> +  ssh_public_key_path             = "~/.ssh/id_rsa.pub"
Consider, as an alternative to inputs.tf editing, setting these via Terraform variable files (a feature added recently to `master`):

https://github.com/moio/scalability-tests/#passing-custom-terraform-variables

Example:
https://github.com/moio/scalability-tests/blob/15e40b283af5ceb56f5713b62f61d9b4bcf57445/terraform/main/ssh/inputs.tf#L41-L49

It is not strictly required but it might help, I will leave that for your consideration.

2023-08-28 12:29 UTC, moio commented on terraform/modules/openstack_network/main.tf
> +  count          = var.network_id == "" ? 1 : 0
Terraform supports `null` as a placeholder value where a variable is not set.

Please use `null` instead of an empty string in all applicable situations.

2023-08-28 12:29 UTC, moio commented on terraform/modules/openstack_host/inputs.tf
> +  type        = string
You can omit types when you specify a defaut, Terraform will deduce it for you.
```suggestion
```

2023-08-28 12:29 UTC, moio commented on terraform/modules/openstack_host/inputs.tf
> +  description = "Openstack Keypair resource"
```suggestion
  description = "Openstack Keypair name"
```

2023-08-28 12:29 UTC, moio commented on terraform/modules/openstack_host/inputs.tf
> +variable "op_keypair" {
I'd prefer not to prefix all backend-specific variable names, I think we can just use "keypair" for simplicity here:

```suggestion
variable "keypair" {
```

2023-08-28 12:29 UTC, moio commented on terraform/modules/openstack_host/inputs.tf
> +  default     = null
```suggestion
```

Default is always assumed to be null until otherwise specified 😉

2023-08-31 12:57 UTC, Lucasgranet commented on terraform/main/openstack/inputs.tf
> +    flavor_name    = "b2-7" // 2vCPU/7Go
c2-* flavors have better CPU freq.

2023-08-31 16:18 UTC, Lucasgranet commented on terraform/modules/openstack_host/inputs.tf
> +  default     = null
Cannot remove this since Terraform needs to know that the variable has a default value.

```console
│ Error: Missing required argument
│ 
│   on ../../modules/openstack_k3s/main.tf line 18, in module "agent_nodes":
│   18: module "agent_nodes" {
│ 
│ The argument "attach_floating_ip_from" is required, but no definition was found.
```

2023-08-31 16:20 UTC, Lucasgranet commented
Hello @moio 

Rebased with your reviews

Lucas,

2023-09-05 08:15 UTC, moio commented on terraform/modules/openstack_host/inputs.tf
> +  default     = null
🤦 you're right.

2023-09-05 09:16 UTC, merged